### ISSUE TITLE
Textarea instead of input for multiline output or input

### ISSUE THREAD

**Issue by nicolashefti** [Appizy/appizy#15]
Currently input and output are rendered as single line element (using the <input> HTML tag).

There should be the possibility to have multiline input and output (using the <textarea> tag). The easiest solution seems to detect if the rowspan of the cell is bigger than 1 to make the switch.

Note: check this works for different kinds of input (text, number, currency, ...).

Example file: [multiline-input.ods.zip](https://github.com/Appizy/appizy/files/1388325/multiline-input.ods.zip)

**Comment by abedalzain** [comment]
I added this feature, so when you have multilines will render textarea instead of input

**Comment by abedalzain** [comment]
Render output
![image](https://user-images.githubusercontent.com/9558960/31650112-80acf810-b31e-11e7-9e57-f6dbeaac91e2.png)

**Comment by nicolashefti** [comment]
Could it be possible to avoid the light grey background for the output? (like for the single line output).
